/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fundamento.view;

/**
 *
 * @author Glenda Alves de Lima
 */
public class BuscarMedico extends javax.swing.JFrame {

    /**
     * Creates new form BuscarMedico
     */
    public BuscarMedico() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPesquisarMedico = new javax.swing.JTextField();
        BotaoAdicionarMedico = new javax.swing.JButton();
        BotaoFecharMedico = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaMedico = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 134));
        setUndecorated(true);

        BotaoAdicionarMedico.setBackground(new java.awt.Color(255, 255, 255));
        BotaoAdicionarMedico.setForeground(new java.awt.Color(0, 0, 204));
        BotaoAdicionarMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/plus.png"))); // NOI18N
        BotaoAdicionarMedico.setText("Adicionar");
        BotaoAdicionarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAdicionarMedicoActionPerformed(evt);
            }
        });

        BotaoFecharMedico.setBackground(new java.awt.Color(255, 255, 255));
        BotaoFecharMedico.setForeground(new java.awt.Color(0, 0, 204));
        BotaoFecharMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/cross.png"))); // NOI18N
        BotaoFecharMedico.setText("Fechar");

        TabelaMedico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Sexo", "Rg", "CPF", "Data Nascimento", "Data Cadastro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaMedico.setRowHeight(25);
        TabelaMedico.setSelectionBackground(new java.awt.Color(153, 204, 255));
        TabelaMedico.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(TabelaMedico);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("BUSCAR MEDICO");

        jLabel2.setText("Pesquisar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtPesquisarMedico)
                        .addGap(33, 33, 33)
                        .addComponent(BotaoAdicionarMedico)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoFecharMedico))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                        .addGap(10, 10, 10)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoAdicionarMedico)
                    .addComponent(BotaoFecharMedico)
                    .addComponent(jLabel2)
                    .addComponent(txtPesquisarMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoAdicionarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAdicionarMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoAdicionarMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAdicionarMedico;
    private javax.swing.JButton BotaoFecharMedico;
    private javax.swing.JTable TabelaMedico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtPesquisarMedico;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the BotaoAdicionarMedico
     */
    public javax.swing.JButton getBotaoAdicionarMedico() {
        return BotaoAdicionarMedico;
    }

    /**
     * @param BotaoAdicionarMedico the BotaoAdicionarMedico to set
     */
    public void setBotaoAdicionarMedico(javax.swing.JButton BotaoAdicionarMedico) {
        this.BotaoAdicionarMedico = BotaoAdicionarMedico;
    }

   

    /**
     * @return the BotaoFecharMedico
     */
    public javax.swing.JButton getBotaoFecharMedico() {
        return BotaoFecharMedico;
    }

    /**
     * @param BotaoFecharMedico the BotaoFecharMedico to set
     */
    public void setBotaoFecharMedico(javax.swing.JButton BotaoFecharMedico) {
        this.BotaoFecharMedico = BotaoFecharMedico;
    }


    /**
     * @return the TabelaMedico
     */
    public javax.swing.JTable getTabelaMedico() {
        return TabelaMedico;
    }

    /**
     * @param TabelaMedico the TabelaMedico to set
     */
    public void setTabelaMedico(javax.swing.JTable TabelaMedico) {
        this.TabelaMedico = TabelaMedico;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the txtPesquisarMedico
     */
    public javax.swing.JTextField getTxtPesquisarMedico() {
        return txtPesquisarMedico;
    }

    /**
     * @param txtPesquisarMedico the txtPesquisarMedico to set
     */
    public void setTxtPesquisarMedico(javax.swing.JTextField txtPesquisarMedico) {
        this.txtPesquisarMedico = txtPesquisarMedico;
    }


}
