/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fundamento.view;

/**
 *
 * @author Glenda Alves de Lima
 */
public class BuscarProduto extends javax.swing.JFrame {

    /**
     * Creates new form BuscarProduto
     */
    public BuscarProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPesquisarProduto = new javax.swing.JTextField();
        BotaoPesquisarProduto = new javax.swing.JButton();
        BotaoAdicionarProduto = new javax.swing.JButton();
        BotaoEditarProduto = new javax.swing.JButton();
        BotaoExcluirProduto = new javax.swing.JButton();
        BotaoFecharProduto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(3, 134));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1360, 575));

        BotaoPesquisarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/search.png"))); // NOI18N
        BotaoPesquisarProduto.setText("Pesquisar");
        BotaoPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPesquisarProdutoActionPerformed(evt);
            }
        });

        BotaoAdicionarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/plus.png"))); // NOI18N
        BotaoAdicionarProduto.setText("Adicionar");
        BotaoAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAdicionarProdutoActionPerformed(evt);
            }
        });

        BotaoEditarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/pencil.png"))); // NOI18N
        BotaoEditarProduto.setText("Editar");

        BotaoExcluirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/cross.png"))); // NOI18N
        BotaoExcluirProduto.setText("Excluir");

        BotaoFecharProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/cross.png"))); // NOI18N
        BotaoFecharProduto.setText("Fechar");

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Fabricante", "Quantidade Estoque", "Quantidade Minina", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotaoAdicionarProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoEditarProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoExcluirProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoFecharProduto)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(txtPesquisarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotaoPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoAdicionarProduto)
                    .addComponent(BotaoEditarProduto)
                    .addComponent(BotaoExcluirProduto)
                    .addComponent(BotaoFecharProduto))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPesquisarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoPesquisarProdutoActionPerformed

    private void BotaoAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAdicionarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoAdicionarProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAdicionarProduto;
    private javax.swing.JButton BotaoEditarProduto;
    private javax.swing.JButton BotaoExcluirProduto;
    private javax.swing.JButton BotaoFecharProduto;
    private javax.swing.JButton BotaoPesquisarProduto;
    private javax.swing.JTable Tabela;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtPesquisarProduto;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the BotaoAdicionarProduto
     */
    public javax.swing.JButton getBotaoAdicionarProduto() {
        return BotaoAdicionarProduto;
    }

    /**
     * @param BotaoAdicionarProduto the BotaoAdicionarProduto to set
     */
    public void setBotaoAdicionarProduto(javax.swing.JButton BotaoAdicionarProduto) {
        this.BotaoAdicionarProduto = BotaoAdicionarProduto;
    }

    /**
     * @return the BotaoEditarProduto
     */
    public javax.swing.JButton getBotaoEditarProduto() {
        return BotaoEditarProduto;
    }

    /**
     * @param BotaoEditarProduto the BotaoEditarProduto to set
     */
    public void setBotaoEditarProduto(javax.swing.JButton BotaoEditarProduto) {
        this.BotaoEditarProduto = BotaoEditarProduto;
    }

    /**
     * @return the BotaoExcluircionarProduto
     */
    public javax.swing.JButton getBotaoExcluirProduto() {
        return BotaoExcluirProduto;
    }

    /**
     * @param BotaoExcluircionarProduto the BotaoExcluircionarProduto to set
     */
    public void setBotaoExcluirProduto(javax.swing.JButton BotaoExcluircionarProduto) {
        this.BotaoExcluirProduto = BotaoExcluircionarProduto;
    }

    /**
     * @return the BotaoFecharProduto
     */
    public javax.swing.JButton getBotaoFecharProduto() {
        return BotaoFecharProduto;
    }

    /**
     * @param BotaoFecharProduto the BotaoFecharProduto to set
     */
    public void setBotaoFecharProduto(javax.swing.JButton BotaoFecharProduto) {
        this.BotaoFecharProduto = BotaoFecharProduto;
    }

    /**
     * @return the BotaoPesquisarProduto
     */
    public javax.swing.JButton getBotaoPesquisarProduto() {
        return BotaoPesquisarProduto;
    }

    /**
     * @param BotaoPesquisarProduto the BotaoPesquisarProduto to set
     */
    public void setBotaoPesquisarProduto(javax.swing.JButton BotaoPesquisarProduto) {
        this.BotaoPesquisarProduto = BotaoPesquisarProduto;
    }

    /**
     * @return the Tabela
     */
    public javax.swing.JTable getTabela() {
        return Tabela;
    }

    /**
     * @param Tabela the Tabela to set
     */
    public void setTabela(javax.swing.JTable Tabela) {
        this.Tabela = Tabela;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the txtPesquisarProduto
     */
    public javax.swing.JTextField getTxtPesquisarProduto() {
        return txtPesquisarProduto;
    }

    /**
     * @param txtPesquisarProduto the txtPesquisarProduto to set
     */
    public void setTxtPesquisarProduto(javax.swing.JTextField txtPesquisarProduto) {
        this.txtPesquisarProduto = txtPesquisarProduto;
    }


}
