/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fundamento.view;

/**
 *
 * @author Glenda Alves de Lima
 */
public class Relatorio extends javax.swing.JFrame {

    /**
     * Creates new form Relatorio
     */
    public Relatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoVoltarRelatorio = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        comboescolha = new javax.swing.JComboBox<>();
        labelescolha = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelarelatorio = new javax.swing.JTable();
        BotaoRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(100, 134));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1160, 500));

        BotaoVoltarRelatorio.setBackground(new java.awt.Color(255, 255, 255));
        BotaoVoltarRelatorio.setForeground(new java.awt.Color(0, 0, 204));
        BotaoVoltarRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/arrow-left-1.png"))); // NOI18N
        BotaoVoltarRelatorio.setText("Voltar");
        BotaoVoltarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarRelatorioActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Felix Titling", 0, 24)); // NOI18N
        jLabel5.setText("rELATORIO Persoais");

        jPanel2.setBackground(new java.awt.Color(0, 57, 69));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        comboescolha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paciente", "Funcionario", "Medico", "Fornecedor" }));
        comboescolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboescolhaActionPerformed(evt);
            }
        });

        labelescolha.setText("Escolha o relatorio :");

        tabelarelatorio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tabelarelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {"", "", null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelarelatorio.setEnabled(false);
        tabelarelatorio.setPreferredSize(new java.awt.Dimension(300, 400));
        tabelarelatorio.setRowHeight(25);
        tabelarelatorio.setSelectionBackground(new java.awt.Color(153, 204, 255));
        tabelarelatorio.setShowHorizontalLines(false);
        tabelarelatorio.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tabelarelatorio);

        BotaoRelatorio.setBackground(new java.awt.Color(255, 255, 255));
        BotaoRelatorio.setForeground(new java.awt.Color(0, 0, 204));
        BotaoRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/stats-2.png"))); // NOI18N
        BotaoRelatorio.setText("Gerar Relatorio");
        BotaoRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelescolha)
                        .addGap(18, 18, 18)
                        .addComponent(comboescolha, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoVoltarRelatorio)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoRelatorio))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoVoltarRelatorio)
                    .addComponent(BotaoRelatorio)
                    .addComponent(labelescolha)
                    .addComponent(comboescolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoVoltarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoVoltarRelatorioActionPerformed

    private void comboescolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboescolhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboescolhaActionPerformed

    private void BotaoRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoRelatorio;
    private javax.swing.JButton BotaoVoltarRelatorio;
    private javax.swing.JComboBox<String> comboescolha;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelescolha;
    private javax.swing.JTable tabelarelatorio;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the BotaoVoltarRelatorio
     */
    public javax.swing.JButton getBotaoVoltarRelatorio() {
        return BotaoVoltarRelatorio;
    }

    /**
     * @param BotaoVoltarRelatorio the BotaoVoltarRelatorio to set
     */
    public void setBotaoVoltarRelatorio(javax.swing.JButton BotaoVoltarRelatorio) {
        this.BotaoVoltarRelatorio = BotaoVoltarRelatorio;
    }

    /**
     * @return the comboescolha
     */
    public javax.swing.JComboBox<String> getComboescolha() {
        return comboescolha;
    }

    /**
     * @param comboescolha the comboescolha to set
     */
    public void setComboescolha(javax.swing.JComboBox<String> comboescolha) {
        this.comboescolha = comboescolha;
    }
    /**
     * @return the jLabel5
     */
    public javax.swing.JLabel getjLabel5() {
        return jLabel5;
    }

    /**
     * @param jLabel5 the jLabel5 to set
     */
    public void setjLabel5(javax.swing.JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    /**
     * @return the jPanel2
     */
    public javax.swing.JPanel getjPanel2() {
        return jPanel2;
    }

    /**
     * @param jPanel2 the jPanel2 to set
     */
    public void setjPanel2(javax.swing.JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the labelescolha
     */
    public javax.swing.JLabel getLabelescolha() {
        return labelescolha;
    }

    /**
     * @param labelescolha the labelescolha to set
     */
    public void setLabelescolha(javax.swing.JLabel labelescolha) {
        this.labelescolha = labelescolha;
    }

    /**
     * @return the tabelarelatorio
     */
    public javax.swing.JTable getTabelarelatorio() {
        return tabelarelatorio;
    }

    /**
     * @param tabelarelatorio the tabelarelatorio to set
     */
    public void setTabelarelatorio(javax.swing.JTable tabelarelatorio) {
        this.tabelarelatorio = tabelarelatorio;
    }

    /**
     * @return the BotaoRelatorio
     */
    public javax.swing.JButton getBotaoRelatorio() {
        return BotaoRelatorio;
    }

    /**
     * @param BotaoRelatorio the BotaoRelatorio to set
     */
    public void setBotaoRelatorio(javax.swing.JButton BotaoRelatorio) {
        this.BotaoRelatorio = BotaoRelatorio;
    }

    


  

}
