/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fundamento.view;

/**
 *
 * @author Glenda Alves de Lima
 */
public class TelaPagamento extends javax.swing.JFrame {

    /**
     * Creates new form Pagamento
     */
    public TelaPagamento() {
        initComponents();
        panelParcela.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtvalortotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ComboPagamento = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtQParcela = new javax.swing.JTextField();
        botaoOk = new javax.swing.JButton();
        panelParcela = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtValorparcela = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtdata_ven_parcela = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        ComboCaixa = new javax.swing.JComboBox<>();
        ComboStatus = new javax.swing.JComboBox<>();
        botaocancelarpacela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 134));
        setPreferredSize(new java.awt.Dimension(800, 500));

        jLabel1.setText("Valor Total:");

        txtvalortotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvalortotalActionPerformed(evt);
            }
        });

        jLabel2.setText("Status:");

        jLabel3.setText("Pagamento:");

        ComboPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cartão Debito", "Cartão Credito", "Cheque", "Dinheiro" }));
        ComboPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboPagamentoActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantidade Parcela:");

        botaoOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/tick.png"))); // NOI18N
        botaoOk.setText("OK");

        panelParcela.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parcela", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        panelParcela.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel9.setText("Valor Parcela:");

        try {
            txtValorparcela.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtValorparcela.setText("");

        jLabel7.setText("Data Vencimento:");

        try {
            txtdata_ven_parcela.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout panelParcelaLayout = new javax.swing.GroupLayout(panelParcela);
        panelParcela.setLayout(panelParcelaLayout);
        panelParcelaLayout.setHorizontalGroup(
            panelParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParcelaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(txtValorparcela, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txtdata_ven_parcela, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addGap(191, 191, 191))
        );
        panelParcelaLayout.setVerticalGroup(
            panelParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelParcelaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorparcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(txtdata_ven_parcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel12.setText("Caixa:");

        ComboCaixa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caixa 1" }));

        ComboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A Vista", "A Prazo" }));

        botaocancelarpacela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/cross.png"))); // NOI18N
        botaocancelarpacela.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtvalortotal, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoOk, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(botaocancelarpacela)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ComboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtvalortotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ComboCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(panelParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoOk)
                    .addComponent(botaocancelarpacela))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtvalortotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvalortotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvalortotalActionPerformed

    private void ComboPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboPagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPagamento().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboCaixa;
    private javax.swing.JComboBox<String> ComboPagamento;
    private javax.swing.JComboBox<String> ComboStatus;
    private javax.swing.JButton botaoOk;
    private javax.swing.JButton botaocancelarpacela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelParcela;
    private javax.swing.JTextField txtQParcela;
    private javax.swing.JFormattedTextField txtValorparcela;
    private javax.swing.JFormattedTextField txtdata_ven_parcela;
    private javax.swing.JTextField txtvalortotal;
    // End of variables declaration//GEN-END:variables

   
    /**
     * @return the botaoOk
     */
    public javax.swing.JButton getBotaoOk() {
        return botaoOk;
    }

    /**
     * @param botaoOk the botaoOk to set
     */
    public void setBotaoOk(javax.swing.JButton botaoOk) {
        this.botaoOk = botaoOk;
    }

    /**
     * @return the ComboCaixa
     */
    public javax.swing.JComboBox<String> getComboCaixa() {
        return ComboCaixa;
    }

    /**
     * @param ComboCaixa the ComboCaixa to set
     */
    public void setComboCaixa(javax.swing.JComboBox<String> ComboCaixa) {
        this.ComboCaixa = ComboCaixa;
    }

    /**
     * @return the ComboPagamento
     */
    public javax.swing.JComboBox<String> getComboPagamento() {
        return ComboPagamento;
    }

    /**
     * @param ComboPagamento the ComboPagamento to set
     */
    public void setComboPagamento(javax.swing.JComboBox<String> ComboPagamento) {
        this.ComboPagamento = ComboPagamento;
    }

    /**
     * @return the ComboStatus
     */
    public javax.swing.JComboBox<String> getComboStatus() {
        return ComboStatus;
    }

    /**
     * @param ComboStatus the ComboStatus to set
     */
    public void setComboStatus(javax.swing.JComboBox<String> ComboStatus) {
        this.ComboStatus = ComboStatus;
    }

 

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @param jLabel1 the jLabel1 to set
     */
    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

   

    /**
     * @return the jLabel12
     */
    public javax.swing.JLabel getjLabel12() {
        return jLabel12;
    }

    /**
     * @param jLabel12 the jLabel12 to set
     */
    public void setjLabel12(javax.swing.JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @param jLabel2 the jLabel2 to set
     */
    public void setjLabel2(javax.swing.JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    /**
     * @return the jLabel3
     */
    public javax.swing.JLabel getjLabel3() {
        return jLabel3;
    }

    /**
     * @param jLabel3 the jLabel3 to set
     */
    public void setjLabel3(javax.swing.JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    /**
     * @return the jLabel4
     */
    public javax.swing.JLabel getjLabel4() {
        return jLabel4;
    }

    /**
     * @param jLabel4 the jLabel4 to set
     */
    public void setjLabel4(javax.swing.JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    
   

    /**
     * @return the jLabel7
     */
    public javax.swing.JLabel getjLabel7() {
        return jLabel7;
    }

    /**
     * @param jLabel7 the jLabel7 to set
     */
    public void setjLabel7(javax.swing.JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    /**
     * @return the jLabel9
     */
    public javax.swing.JLabel getjLabel9() {
        return jLabel9;
    }

    /**
     * @param jLabel9 the jLabel9 to set
     */
    public void setjLabel9(javax.swing.JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    /**
     * @return the panelParcela
     */
    public javax.swing.JPanel getPanelParcela() {
        return panelParcela;
    }

    /**
     * @param panelParcela the panelParcela to set
     */
    public void setPanelParcela(javax.swing.JPanel panelParcela) {
        this.panelParcela = panelParcela;
    }

    /**
     * @return the txtQParcela
     */
    public javax.swing.JTextField getTxtQParcela() {
        return txtQParcela;
    }

    /**
     * @param txtQParcela the txtQParcela to set
     */
    public void setTxtQParcela(javax.swing.JTextField txtQParcela) {
        this.txtQParcela = txtQParcela;
    }

    /**
     * @return the txtValorparcela
     */
    public javax.swing.JFormattedTextField getTxtValorparcela() {
        return txtValorparcela;
    }

    /**
     * @param txtValorparcela the txtValorparcela to set
     */
    public void setTxtValorparcela(javax.swing.JFormattedTextField txtValorparcela) {
        this.txtValorparcela = txtValorparcela;
    }

    

    /**
     * @return the txtdata_ven_parcela
     */
    public javax.swing.JFormattedTextField getTxtdata_ven_parcela() {
        return txtdata_ven_parcela;
    }

    /**
     * @param txtdata_ven_parcela the txtdata_ven_parcela to set
     */
    public void setTxtdata_ven_parcela(javax.swing.JFormattedTextField txtdata_ven_parcela) {
        this.txtdata_ven_parcela = txtdata_ven_parcela;
    }




    /**
     * @return the txtvalortotal
     */
    public javax.swing.JTextField getTxtvalortotal() {
        return txtvalortotal;
    }

    /**
     * @param txtvalortotal the txtvalortotal to set
     */
    public void setTxtvalortotal(javax.swing.JTextField txtvalortotal) {
        this.txtvalortotal = txtvalortotal;
    }

    /**
     * @return the botaocancelarpacela
     */
    public javax.swing.JButton getBotaocancelarpacela() {
        return botaocancelarpacela;
    }

    /**
     * @param botaocancelarpacela the botaocancelarpacela to set
     */
    public void setBotaocancelarpacela(javax.swing.JButton botaocancelarpacela) {
        this.botaocancelarpacela = botaocancelarpacela;
    }

}
