/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fundamento.view;

/**
 *
 * @author Glenda Alves de Lima
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * @return the BotaoCadastroPaciente
     */
   

    
   
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
         
       this.setExtendedState(MAXIMIZED_BOTH);
       PanelConsultorio.setVisible(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelP = new javax.swing.JTabbedPane();
        PanelPrincipal = new javax.swing.JPanel();
        BotaoCadastroPaciente = new javax.swing.JButton();
        BotaoCadastroFuncionario = new javax.swing.JButton();
        BotaoMedico = new javax.swing.JButton();
        Botaolist = new javax.swing.JButton();
        BotaoCadastrarTarefa = new javax.swing.JButton();
        BotaoSair = new javax.swing.JButton();
        BotaoLogoff = new javax.swing.JButton();
        BotaoAgendamento = new javax.swing.JButton();
        PanelFinanceiro = new javax.swing.JPanel();
        botaocontareceber = new javax.swing.JButton();
        BotaofluxodeCaixa = new javax.swing.JButton();
        botaocontapagar = new javax.swing.JButton();
        BotaoRecibo = new javax.swing.JButton();
        PanelDadosEstoque = new javax.swing.JPanel();
        BotaoEntradaEstoque = new javax.swing.JButton();
        botaoSaidaEstoque = new javax.swing.JButton();
        BotaoCadastarProduto = new javax.swing.JButton();
        BotaoCadastroFornecedor = new javax.swing.JButton();
        PanelRelatorio = new javax.swing.JPanel();
        BotaoRelatorioPessoais = new javax.swing.JButton();
        BotaoRelatorioConsulta = new javax.swing.JButton();
        BotaoRelatorioProduto = new javax.swing.JButton();
        BotaoRelatorioFluxoCaixa = new javax.swing.JButton();
        BotaoRelatorioTarefa = new javax.swing.JButton();
        PanelDadosConsultorio = new javax.swing.JPanel();
        BotaoAtualizardados = new javax.swing.JButton();
        PanelConsultorio = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lblnome = new javax.swing.JLabel();
        txtrazao = new javax.swing.JTextField();
        txtcnpj = new javax.swing.JFormattedTextField();
        lblcnpj = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnomefantasia = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        txtcidade = new javax.swing.JTextField();
        txtrua = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnumero = new javax.swing.JTextField();
        txtbairro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUf = new javax.swing.JComboBox();
        lblendereco = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcep = new javax.swing.JFormattedTextField();
        jPanel9 = new javax.swing.JPanel();
        txtemail = new javax.swing.JTextField();
        lblemail = new javax.swing.JLabel();
        txttelefone = new javax.swing.JFormattedTextField();
        lbltelefone = new javax.swing.JLabel();
        txtcelular = new javax.swing.JFormattedTextField();
        lbltelefone1 = new javax.swing.JLabel();
        BotaoSalvarConsultorio = new javax.swing.JButton();
        BotaoCancelarrConsultorio = new javax.swing.JButton();
        labeltarefa = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(57, 167, 167));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));

        panelP.setBackground(new java.awt.Color(255, 255, 255));
        panelP.setForeground(new java.awt.Color(0, 102, 102));
        panelP.setToolTipText("");

        PanelPrincipal.setBackground(new java.awt.Color(0, 57, 69));

        BotaoCadastroPaciente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotaoCadastroPaciente.setForeground(new java.awt.Color(204, 204, 204));
        BotaoCadastroPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/Paciente.png"))); // NOI18N
        BotaoCadastroPaciente.setText("Paciente");
        BotaoCadastroPaciente.setBorderPainted(false);
        BotaoCadastroPaciente.setContentAreaFilled(false);
        BotaoCadastroPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoCadastroPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotaoCadastroPaciente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotaoCadastroPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastroPacienteActionPerformed(evt);
            }
        });

        BotaoCadastroFuncionario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotaoCadastroFuncionario.setForeground(new java.awt.Color(204, 204, 204));
        BotaoCadastroFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/Cadastro.png"))); // NOI18N
        BotaoCadastroFuncionario.setText("Fucionario");
        BotaoCadastroFuncionario.setBorderPainted(false);
        BotaoCadastroFuncionario.setContentAreaFilled(false);
        BotaoCadastroFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoCadastroFuncionario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotaoCadastroFuncionario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotaoCadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastroFuncionarioActionPerformed(evt);
            }
        });

        BotaoMedico.setBackground(new java.awt.Color(204, 204, 204));
        BotaoMedico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotaoMedico.setForeground(new java.awt.Color(204, 204, 204));
        BotaoMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/Profissional.png"))); // NOI18N
        BotaoMedico.setText("Profissionais");
        BotaoMedico.setBorderPainted(false);
        BotaoMedico.setContentAreaFilled(false);
        BotaoMedico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoMedico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotaoMedico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotaoMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoMedicoActionPerformed(evt);
            }
        });

        Botaolist.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Botaolist.setForeground(new java.awt.Color(204, 204, 204));
        Botaolist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/Agendamento.png"))); // NOI18N
        Botaolist.setText("Agenda");
        Botaolist.setBorderPainted(false);
        Botaolist.setContentAreaFilled(false);
        Botaolist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Botaolist.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Botaolist.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Botaolist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaolistActionPerformed(evt);
            }
        });

        BotaoCadastrarTarefa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotaoCadastrarTarefa.setForeground(new java.awt.Color(204, 204, 204));
        BotaoCadastrarTarefa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/Ferramentas.png"))); // NOI18N
        BotaoCadastrarTarefa.setText("Tarefa");
        BotaoCadastrarTarefa.setBorderPainted(false);
        BotaoCadastrarTarefa.setContentAreaFilled(false);
        BotaoCadastrarTarefa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoCadastrarTarefa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotaoCadastrarTarefa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotaoCadastrarTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarTarefaActionPerformed(evt);
            }
        });

        BotaoSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotaoSair.setForeground(new java.awt.Color(204, 204, 204));
        BotaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/Sair.png"))); // NOI18N
        BotaoSair.setText("Sair");
        BotaoSair.setBorderPainted(false);
        BotaoSair.setContentAreaFilled(false);
        BotaoSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotaoSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSairActionPerformed(evt);
            }
        });

        BotaoLogoff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotaoLogoff.setForeground(new java.awt.Color(204, 204, 204));
        BotaoLogoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/Logoff.png"))); // NOI18N
        BotaoLogoff.setText("Logoff");
        BotaoLogoff.setBorderPainted(false);
        BotaoLogoff.setContentAreaFilled(false);
        BotaoLogoff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoLogoff.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotaoLogoff.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotaoLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLogoffActionPerformed(evt);
            }
        });

        BotaoAgendamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotaoAgendamento.setForeground(new java.awt.Color(204, 204, 204));
        BotaoAgendamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/Agendamento.png"))); // NOI18N
        BotaoAgendamento.setText("Agenda de Consulta");
        BotaoAgendamento.setBorderPainted(false);
        BotaoAgendamento.setContentAreaFilled(false);
        BotaoAgendamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoAgendamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotaoAgendamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotaoAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAgendamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addComponent(BotaoCadastroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoMedico)
                .addGap(18, 18, 18)
                .addComponent(BotaoCadastroFuncionario)
                .addGap(18, 18, 18)
                .addComponent(BotaoCadastrarTarefa)
                .addGap(18, 18, 18)
                .addComponent(BotaoAgendamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Botaolist)
                .addGap(28, 28, 28)
                .addComponent(BotaoLogoff)
                .addGap(29, 29, 29)
                .addComponent(BotaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoCadastrarTarefa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoAgendamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Botaolist)
                            .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(BotaoCadastroFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotaoMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotaoCadastroPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotaoLogoff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(BotaoSair, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panelP.addTab("PRINCIPAL", PanelPrincipal);

        PanelFinanceiro.setBackground(new java.awt.Color(0, 57, 69));

        botaocontareceber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaocontareceber.setForeground(new java.awt.Color(204, 204, 204));
        botaocontareceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/EntradadeProduto.png"))); // NOI18N
        botaocontareceber.setText("Contas a receber");
        botaocontareceber.setBorderPainted(false);
        botaocontareceber.setContentAreaFilled(false);
        botaocontareceber.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaocontareceber.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaocontareceber.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaocontareceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaocontareceberActionPerformed(evt);
            }
        });

        BotaofluxodeCaixa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotaofluxodeCaixa.setForeground(new java.awt.Color(204, 204, 204));
        BotaofluxodeCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/Financeiro.png"))); // NOI18N
        BotaofluxodeCaixa.setText("Fluxo Caixa");
        BotaofluxodeCaixa.setBorderPainted(false);
        BotaofluxodeCaixa.setContentAreaFilled(false);
        BotaofluxodeCaixa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaofluxodeCaixa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotaofluxodeCaixa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotaofluxodeCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaofluxodeCaixaActionPerformed(evt);
            }
        });

        botaocontapagar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaocontapagar.setForeground(new java.awt.Color(204, 204, 204));
        botaocontapagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/SaidadeProduto.png"))); // NOI18N
        botaocontapagar.setText("Contas a pagar");
        botaocontapagar.setBorderPainted(false);
        botaocontapagar.setContentAreaFilled(false);
        botaocontapagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaocontapagar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaocontapagar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaocontapagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaocontapagarActionPerformed(evt);
            }
        });

        BotaoRecibo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotaoRecibo.setForeground(new java.awt.Color(204, 204, 204));
        BotaoRecibo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/Procedimentos.png"))); // NOI18N
        BotaoRecibo.setText("Recibo");
        BotaoRecibo.setBorderPainted(false);
        BotaoRecibo.setContentAreaFilled(false);
        BotaoRecibo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoRecibo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotaoRecibo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotaoRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoReciboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelFinanceiroLayout = new javax.swing.GroupLayout(PanelFinanceiro);
        PanelFinanceiro.setLayout(PanelFinanceiroLayout);
        PanelFinanceiroLayout.setHorizontalGroup(
            PanelFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFinanceiroLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(BotaofluxodeCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaocontareceber, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(botaocontapagar)
                .addGap(28, 28, 28)
                .addComponent(BotaoRecibo)
                .addContainerGap(591, Short.MAX_VALUE))
        );
        PanelFinanceiroLayout.setVerticalGroup(
            PanelFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFinanceiroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaocontareceber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaofluxodeCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaocontapagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoRecibo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelP.addTab("FINANCEIRO   ", PanelFinanceiro);

        PanelDadosEstoque.setBackground(new java.awt.Color(0, 57, 69));

        BotaoEntradaEstoque.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotaoEntradaEstoque.setForeground(new java.awt.Color(204, 204, 204));
        BotaoEntradaEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/EntradadeProduto.png"))); // NOI18N
        BotaoEntradaEstoque.setText("Entrada de Produtos");
        BotaoEntradaEstoque.setBorderPainted(false);
        BotaoEntradaEstoque.setContentAreaFilled(false);
        BotaoEntradaEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoEntradaEstoque.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotaoEntradaEstoque.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotaoEntradaEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEntradaEstoqueActionPerformed(evt);
            }
        });

        botaoSaidaEstoque.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoSaidaEstoque.setForeground(new java.awt.Color(204, 204, 204));
        botaoSaidaEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/SaidadeProduto.png"))); // NOI18N
        botaoSaidaEstoque.setText("Saida Estoque");
        botaoSaidaEstoque.setBorderPainted(false);
        botaoSaidaEstoque.setContentAreaFilled(false);
        botaoSaidaEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoSaidaEstoque.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoSaidaEstoque.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoSaidaEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSaidaEstoqueActionPerformed(evt);
            }
        });

        BotaoCadastarProduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotaoCadastarProduto.setForeground(new java.awt.Color(204, 204, 204));
        BotaoCadastarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/Produto.png"))); // NOI18N
        BotaoCadastarProduto.setText("Produto");
        BotaoCadastarProduto.setBorderPainted(false);
        BotaoCadastarProduto.setContentAreaFilled(false);
        BotaoCadastarProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoCadastarProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotaoCadastarProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotaoCadastarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastarProdutoActionPerformed(evt);
            }
        });

        BotaoCadastroFornecedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotaoCadastroFornecedor.setForeground(new java.awt.Color(204, 204, 204));
        BotaoCadastroFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/Fornecedor.png"))); // NOI18N
        BotaoCadastroFornecedor.setText("Fornecedor");
        BotaoCadastroFornecedor.setBorderPainted(false);
        BotaoCadastroFornecedor.setContentAreaFilled(false);
        BotaoCadastroFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoCadastroFornecedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotaoCadastroFornecedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotaoCadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastroFornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDadosEstoqueLayout = new javax.swing.GroupLayout(PanelDadosEstoque);
        PanelDadosEstoque.setLayout(PanelDadosEstoqueLayout);
        PanelDadosEstoqueLayout.setHorizontalGroup(
            PanelDadosEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDadosEstoqueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotaoCadastarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotaoCadastroFornecedor)
                .addGap(31, 31, 31)
                .addComponent(botaoSaidaEstoque)
                .addGap(27, 27, 27)
                .addComponent(BotaoEntradaEstoque)
                .addContainerGap(567, Short.MAX_VALUE))
        );
        PanelDadosEstoqueLayout.setVerticalGroup(
            PanelDadosEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDadosEstoqueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDadosEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoEntradaEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelDadosEstoqueLayout.createSequentialGroup()
                        .addGroup(PanelDadosEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotaoCadastroFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotaoCadastarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoSaidaEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panelP.addTab("ESTOQUE", PanelDadosEstoque);

        PanelRelatorio.setBackground(new java.awt.Color(0, 57, 69));

        BotaoRelatorioPessoais.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotaoRelatorioPessoais.setForeground(new java.awt.Color(204, 204, 204));
        BotaoRelatorioPessoais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/Relatorio.png"))); // NOI18N
        BotaoRelatorioPessoais.setText("Relatorios Pessoais");
        BotaoRelatorioPessoais.setBorderPainted(false);
        BotaoRelatorioPessoais.setContentAreaFilled(false);
        BotaoRelatorioPessoais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoRelatorioPessoais.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotaoRelatorioPessoais.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotaoRelatorioPessoais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRelatorioPessoaisActionPerformed(evt);
            }
        });

        BotaoRelatorioConsulta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotaoRelatorioConsulta.setForeground(new java.awt.Color(204, 204, 204));
        BotaoRelatorioConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/Relatorio.png"))); // NOI18N
        BotaoRelatorioConsulta.setText("Relatorio de Consulta");
        BotaoRelatorioConsulta.setBorderPainted(false);
        BotaoRelatorioConsulta.setContentAreaFilled(false);
        BotaoRelatorioConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoRelatorioConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotaoRelatorioConsulta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotaoRelatorioConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRelatorioConsultaActionPerformed(evt);
            }
        });

        BotaoRelatorioProduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotaoRelatorioProduto.setForeground(new java.awt.Color(204, 204, 204));
        BotaoRelatorioProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/Relatorio.png"))); // NOI18N
        BotaoRelatorioProduto.setText("Relatorio de Produto");
        BotaoRelatorioProduto.setBorderPainted(false);
        BotaoRelatorioProduto.setContentAreaFilled(false);
        BotaoRelatorioProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoRelatorioProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotaoRelatorioProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotaoRelatorioProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRelatorioProdutoActionPerformed(evt);
            }
        });

        BotaoRelatorioFluxoCaixa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotaoRelatorioFluxoCaixa.setForeground(new java.awt.Color(204, 204, 204));
        BotaoRelatorioFluxoCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/Relatorio.png"))); // NOI18N
        BotaoRelatorioFluxoCaixa.setText("Relatorio Fluxo Caixa");
        BotaoRelatorioFluxoCaixa.setBorderPainted(false);
        BotaoRelatorioFluxoCaixa.setContentAreaFilled(false);
        BotaoRelatorioFluxoCaixa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoRelatorioFluxoCaixa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotaoRelatorioFluxoCaixa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotaoRelatorioFluxoCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRelatorioFluxoCaixaActionPerformed(evt);
            }
        });

        BotaoRelatorioTarefa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotaoRelatorioTarefa.setForeground(new java.awt.Color(204, 204, 204));
        BotaoRelatorioTarefa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/Relatorio.png"))); // NOI18N
        BotaoRelatorioTarefa.setText("Relatorio de Tarefa");
        BotaoRelatorioTarefa.setBorderPainted(false);
        BotaoRelatorioTarefa.setContentAreaFilled(false);
        BotaoRelatorioTarefa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoRelatorioTarefa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotaoRelatorioTarefa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotaoRelatorioTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRelatorioTarefaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelRelatorioLayout = new javax.swing.GroupLayout(PanelRelatorio);
        PanelRelatorio.setLayout(PanelRelatorioLayout);
        PanelRelatorioLayout.setHorizontalGroup(
            PanelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRelatorioLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(BotaoRelatorioPessoais)
                .addGap(18, 18, 18)
                .addComponent(BotaoRelatorioConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotaoRelatorioProduto)
                .addGap(18, 18, 18)
                .addComponent(BotaoRelatorioTarefa)
                .addGap(17, 17, 17)
                .addComponent(BotaoRelatorioFluxoCaixa)
                .addContainerGap(256, Short.MAX_VALUE))
        );
        PanelRelatorioLayout.setVerticalGroup(
            PanelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRelatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotaoRelatorioProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoRelatorioPessoais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoRelatorioConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoRelatorioFluxoCaixa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoRelatorioTarefa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelP.addTab("RELATORIO   ", PanelRelatorio);

        PanelDadosConsultorio.setBackground(new java.awt.Color(0, 57, 69));

        BotaoAtualizardados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotaoAtualizardados.setForeground(new java.awt.Color(204, 204, 204));
        BotaoAtualizardados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/Procedimentos.png"))); // NOI18N
        BotaoAtualizardados.setText("Atualizar Dados");
        BotaoAtualizardados.setBorderPainted(false);
        BotaoAtualizardados.setContentAreaFilled(false);
        BotaoAtualizardados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoAtualizardados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotaoAtualizardados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotaoAtualizardados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAtualizardadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDadosConsultorioLayout = new javax.swing.GroupLayout(PanelDadosConsultorio);
        PanelDadosConsultorio.setLayout(PanelDadosConsultorioLayout);
        PanelDadosConsultorioLayout.setHorizontalGroup(
            PanelDadosConsultorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDadosConsultorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotaoAtualizardados)
                .addContainerGap(1056, Short.MAX_VALUE))
        );
        PanelDadosConsultorioLayout.setVerticalGroup(
            PanelDadosConsultorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDadosConsultorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotaoAtualizardados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        panelP.addTab("DADOS CONSULTORIO", PanelDadosConsultorio);

        PanelConsultorio.setPreferredSize(new java.awt.Dimension(1160, 610));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consultorio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        lblnome.setText("Razão Socia:l");

        try {
            txtcnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcnpjFocusLost(evt);
            }
        });
        txtcnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcnpjActionPerformed(evt);
            }
        });

        lblcnpj.setText("CNPJ:");

        jLabel7.setText("Nome Fantasia:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnome)
                            .addComponent(lblcnpj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtrazao)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnomefantasia)))
                .addGap(50, 50, 50))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcnpj)
                    .addComponent(txtcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnome)
                    .addComponent(txtrazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtnomefantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel3.setText("Rua:");

        jLabel4.setText("Número:");

        jLabel5.setText("Bairro:");

        jLabel6.setText("UF:");

        txtUf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        lblendereco.setText("Cidade:");

        jLabel2.setText("Cep:");

        try {
            txtcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(lblendereco))
                .addGap(17, 17, 17)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtrua, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(txtnumero, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcep, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtbairro, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(txtcidade)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtUf, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtrua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txtcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        lblemail.setText("E-mail:");

        try {
            txttelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbltelefone.setText("Telefone:");

        try {
            txtcelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbltelefone1.setText("Celular:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(lbltelefone)
                .addGap(18, 18, 18)
                .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltelefone1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblemail)
                .addGap(22, 22, 22)
                .addComponent(txtemail)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblemail))
                .addGap(13, 13, 13)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbltelefone1))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbltelefone)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BotaoSalvarConsultorio.setBackground(new java.awt.Color(255, 255, 255));
        BotaoSalvarConsultorio.setForeground(new java.awt.Color(0, 0, 204));
        BotaoSalvarConsultorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/tick.png"))); // NOI18N
        BotaoSalvarConsultorio.setText("Atualizar");

        BotaoCancelarrConsultorio.setBackground(new java.awt.Color(255, 255, 255));
        BotaoCancelarrConsultorio.setForeground(new java.awt.Color(0, 0, 204));
        BotaoCancelarrConsultorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fundamento/resource/cross.png"))); // NOI18N
        BotaoCancelarrConsultorio.setText("Cancelar");
        BotaoCancelarrConsultorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarrConsultorioActionPerformed(evt);
            }
        });

        labeltarefa.setFont(new java.awt.Font("Felix Titling", 0, 24)); // NOI18N
        labeltarefa.setText("Atualizar Consultorio");

        jPanel10.setBackground(new java.awt.Color(0, 57, 69));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelConsultorioLayout = new javax.swing.GroupLayout(PanelConsultorio);
        PanelConsultorio.setLayout(PanelConsultorioLayout);
        PanelConsultorioLayout.setHorizontalGroup(
            PanelConsultorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelConsultorioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotaoSalvarConsultorio)
                .addGap(18, 18, 18)
                .addComponent(BotaoCancelarrConsultorio)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelConsultorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelConsultorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labeltarefa))
                .addContainerGap())
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelConsultorioLayout.setVerticalGroup(
            PanelConsultorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labeltarefa)
                .addGap(0, 0, 0)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(PanelConsultorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoCancelarrConsultorio)
                    .addComponent(BotaoSalvarConsultorio))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(PanelConsultorio, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                .addGap(123, 123, 123))
            .addComponent(panelP, javax.swing.GroupLayout.DEFAULT_SIZE, 1130, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelP, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(437, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoCadastroPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastroPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoCadastroPacienteActionPerformed

    private void BotaoCadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastroFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoCadastroFornecedorActionPerformed

    private void BotaoCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastroFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoCadastroFuncionarioActionPerformed

    private void BotaoCadastarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoCadastarProdutoActionPerformed

    private void BotaoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoMedicoActionPerformed

    private void BotaolistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaolistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaolistActionPerformed

    private void BotaoCadastrarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarTarefaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoCadastrarTarefaActionPerformed

    private void BotaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoSairActionPerformed

    private void BotaoAtualizardadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAtualizardadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoAtualizardadosActionPerformed

    private void BotaoLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLogoffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoLogoffActionPerformed

    private void BotaofluxodeCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaofluxodeCaixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaofluxodeCaixaActionPerformed

    private void txtcnpjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcnpjFocusLost

    }//GEN-LAST:event_txtcnpjFocusLost

    private void txtcnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcnpjActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void BotaoCancelarrConsultorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarrConsultorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoCancelarrConsultorioActionPerformed

    private void BotaoEntradaEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEntradaEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoEntradaEstoqueActionPerformed

    private void botaocontareceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaocontareceberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaocontareceberActionPerformed

    private void botaoSaidaEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSaidaEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSaidaEstoqueActionPerformed

    private void BotaoRelatorioPessoaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRelatorioPessoaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoRelatorioPessoaisActionPerformed

    private void BotaoRelatorioConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRelatorioConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoRelatorioConsultaActionPerformed

    private void BotaoRelatorioProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRelatorioProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoRelatorioProdutoActionPerformed

    private void BotaoRelatorioFluxoCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRelatorioFluxoCaixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoRelatorioFluxoCaixaActionPerformed

    private void BotaoRelatorioTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRelatorioTarefaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoRelatorioTarefaActionPerformed

    private void botaocontapagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaocontapagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaocontapagarActionPerformed

    private void BotaoReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoReciboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoReciboActionPerformed

    private void BotaoAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAgendamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoAgendamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAgendamento;
    private javax.swing.JButton BotaoAtualizardados;
    private javax.swing.JButton BotaoCadastarProduto;
    private javax.swing.JButton BotaoCadastrarTarefa;
    private javax.swing.JButton BotaoCadastroFornecedor;
    private javax.swing.JButton BotaoCadastroFuncionario;
    private javax.swing.JButton BotaoCadastroPaciente;
    private javax.swing.JButton BotaoCancelarrConsultorio;
    private javax.swing.JButton BotaoEntradaEstoque;
    private javax.swing.JButton BotaoLogoff;
    private javax.swing.JButton BotaoMedico;
    private javax.swing.JButton BotaoRecibo;
    private javax.swing.JButton BotaoRelatorioConsulta;
    private javax.swing.JButton BotaoRelatorioFluxoCaixa;
    private javax.swing.JButton BotaoRelatorioPessoais;
    private javax.swing.JButton BotaoRelatorioProduto;
    private javax.swing.JButton BotaoRelatorioTarefa;
    private javax.swing.JButton BotaoSair;
    private javax.swing.JButton BotaoSalvarConsultorio;
    private javax.swing.JButton BotaofluxodeCaixa;
    private javax.swing.JButton Botaolist;
    private javax.swing.JPanel PanelConsultorio;
    private javax.swing.JPanel PanelDadosConsultorio;
    private javax.swing.JPanel PanelDadosEstoque;
    private javax.swing.JPanel PanelFinanceiro;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel PanelRelatorio;
    private javax.swing.JButton botaoSaidaEstoque;
    private javax.swing.JButton botaocontapagar;
    private javax.swing.JButton botaocontareceber;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel labeltarefa;
    private javax.swing.JLabel lblcnpj;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblendereco;
    private javax.swing.JLabel lblnome;
    private javax.swing.JLabel lbltelefone;
    private javax.swing.JLabel lbltelefone1;
    private javax.swing.JTabbedPane panelP;
    private javax.swing.JComboBox txtUf;
    private javax.swing.JTextField txtbairro;
    private javax.swing.JFormattedTextField txtcelular;
    private javax.swing.JFormattedTextField txtcep;
    private javax.swing.JTextField txtcidade;
    private javax.swing.JFormattedTextField txtcnpj;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnomefantasia;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtrazao;
    private javax.swing.JTextField txtrua;
    private javax.swing.JFormattedTextField txttelefone;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the BotaoAgendamento
     */
    public javax.swing.JButton getBotaoAgendamento() {
        return BotaoAgendamento;
    }

    /**
     * @param BotaoAgendamento the BotaoAgendamento to set
     */
    public void setBotaoAgendamento(javax.swing.JButton BotaoAgendamento) {
        this.BotaoAgendamento = BotaoAgendamento;
    }

    /**
     * @return the BotaoAtualizardados
     */
    public javax.swing.JButton getBotaoAtualizardados() {
        return BotaoAtualizardados;
    }

    /**
     * @param BotaoAtualizardados the BotaoAtualizardados to set
     */
    public void setBotaoAtualizardados(javax.swing.JButton BotaoAtualizardados) {
        this.BotaoAtualizardados = BotaoAtualizardados;
    }

    /**
     * @return the BotaoCadastarProduto
     */
    public javax.swing.JButton getBotaoCadastarProduto() {
        return BotaoCadastarProduto;
    }

    /**
     * @param BotaoCadastarProduto the BotaoCadastarProduto to set
     */
    public void setBotaoCadastarProduto(javax.swing.JButton BotaoCadastarProduto) {
        this.BotaoCadastarProduto = BotaoCadastarProduto;
    }

    /**
     * @return the BotaoCadastrarTarefa
     */
    public javax.swing.JButton getBotaoCadastrarTarefa() {
        return BotaoCadastrarTarefa;
    }

    /**
     * @param BotaoCadastrarTarefa the BotaoCadastrarTarefa to set
     */
    public void setBotaoCadastrarTarefa(javax.swing.JButton BotaoCadastrarTarefa) {
        this.BotaoCadastrarTarefa = BotaoCadastrarTarefa;
    }

    /**
     * @return the BotaoCadastroFornecedor
     */
    public javax.swing.JButton getBotaoCadastroFornecedor() {
        return BotaoCadastroFornecedor;
    }

    /**
     * @param BotaoCadastroFornecedor the BotaoCadastroFornecedor to set
     */
    public void setBotaoCadastroFornecedor(javax.swing.JButton BotaoCadastroFornecedor) {
        this.BotaoCadastroFornecedor = BotaoCadastroFornecedor;
    }

    /**
     * @return the BotaoCadastroFuncionario
     */
    public javax.swing.JButton getBotaoCadastroFuncionario() {
        return BotaoCadastroFuncionario;
    }

    /**
     * @param BotaoCadastroFuncionario the BotaoCadastroFuncionario to set
     */
    public void setBotaoCadastroFuncionario(javax.swing.JButton BotaoCadastroFuncionario) {
        this.BotaoCadastroFuncionario = BotaoCadastroFuncionario;
    }

    /**
     * @return the BotaoCadastroPaciente
     */
    public javax.swing.JButton getBotaoCadastroPaciente() {
        return BotaoCadastroPaciente;
    }

    /**
     * @param BotaoCadastroPaciente the BotaoCadastroPaciente to set
     */
    public void setBotaoCadastroPaciente(javax.swing.JButton BotaoCadastroPaciente) {
        this.BotaoCadastroPaciente = BotaoCadastroPaciente;
    }

    /**
     * @return the BotaoCancelarrConsultorio
     */
    public javax.swing.JButton getBotaoCancelarrConsultorio() {
        return BotaoCancelarrConsultorio;
    }

    /**
     * @param BotaoCancelarrConsultorio the BotaoCancelarrConsultorio to set
     */
    public void setBotaoCancelarrConsultorio(javax.swing.JButton BotaoCancelarrConsultorio) {
        this.BotaoCancelarrConsultorio = BotaoCancelarrConsultorio;
    }

    /**
     * @return the BotaoEntradaEstoque
     */
    public javax.swing.JButton getBotaoEntradaEstoque() {
        return BotaoEntradaEstoque;
    }

    /**
     * @param BotaoEntradaEstoque the BotaoEntradaEstoque to set
     */
    public void setBotaoEntradaEstoque(javax.swing.JButton BotaoEntradaEstoque) {
        this.BotaoEntradaEstoque = BotaoEntradaEstoque;
    }

    /**
     * @return the BotaoLogoff
     */
    public javax.swing.JButton getBotaoLogoff() {
        return BotaoLogoff;
    }

    /**
     * @param BotaoLogoff the BotaoLogoff to set
     */
    public void setBotaoLogoff(javax.swing.JButton BotaoLogoff) {
        this.BotaoLogoff = BotaoLogoff;
    }

    /**
     * @return the BotaoMedico
     */
    public javax.swing.JButton getBotaoMedico() {
        return BotaoMedico;
    }

    /**
     * @param BotaoMedico the BotaoMedico to set
     */
    public void setBotaoMedico(javax.swing.JButton BotaoMedico) {
        this.BotaoMedico = BotaoMedico;
    }

    /**
     * @return the BotaoRecibo
     */
    public javax.swing.JButton getBotaoRecibo() {
        return BotaoRecibo;
    }

    /**
     * @param BotaoRecibo the BotaoRecibo to set
     */
    public void setBotaoRecibo(javax.swing.JButton BotaoRecibo) {
        this.BotaoRecibo = BotaoRecibo;
    }

    /**
     * @return the BotaoRelatorioConsulta
     */
    public javax.swing.JButton getBotaoRelatorioConsulta() {
        return BotaoRelatorioConsulta;
    }

    /**
     * @param BotaoRelatorioConsulta the BotaoRelatorioConsulta to set
     */
    public void setBotaoRelatorioConsulta(javax.swing.JButton BotaoRelatorioConsulta) {
        this.BotaoRelatorioConsulta = BotaoRelatorioConsulta;
    }

    /**
     * @return the BotaoRelatorioFluxoCaixa
     */
    public javax.swing.JButton getBotaoRelatorioFluxoCaixa() {
        return BotaoRelatorioFluxoCaixa;
    }

    /**
     * @param BotaoRelatorioFluxoCaixa the BotaoRelatorioFluxoCaixa to set
     */
    public void setBotaoRelatorioFluxoCaixa(javax.swing.JButton BotaoRelatorioFluxoCaixa) {
        this.BotaoRelatorioFluxoCaixa = BotaoRelatorioFluxoCaixa;
    }

    /**
     * @return the BotaoRelatorioPessoais
     */
    public javax.swing.JButton getBotaoRelatorioPessoais() {
        return BotaoRelatorioPessoais;
    }

    /**
     * @param BotaoRelatorioPessoais the BotaoRelatorioPessoais to set
     */
    public void setBotaoRelatorioPessoais(javax.swing.JButton BotaoRelatorioPessoais) {
        this.BotaoRelatorioPessoais = BotaoRelatorioPessoais;
    }

    /**
     * @return the BotaoRelatorioProduto
     */
    public javax.swing.JButton getBotaoRelatorioProduto() {
        return BotaoRelatorioProduto;
    }

    /**
     * @param BotaoRelatorioProduto the BotaoRelatorioProduto to set
     */
    public void setBotaoRelatorioProduto(javax.swing.JButton BotaoRelatorioProduto) {
        this.BotaoRelatorioProduto = BotaoRelatorioProduto;
    }

    /**
     * @return the BotaoRelatorioTarefa
     */
    public javax.swing.JButton getBotaoRelatorioTarefa() {
        return BotaoRelatorioTarefa;
    }

    /**
     * @param BotaoRelatorioTarefa the BotaoRelatorioTarefa to set
     */
    public void setBotaoRelatorioTarefa(javax.swing.JButton BotaoRelatorioTarefa) {
        this.BotaoRelatorioTarefa = BotaoRelatorioTarefa;
    }

    /**
     * @return the BotaoSair
     */
    public javax.swing.JButton getBotaoSair() {
        return BotaoSair;
    }

    /**
     * @param BotaoSair the BotaoSair to set
     */
    public void setBotaoSair(javax.swing.JButton BotaoSair) {
        this.BotaoSair = BotaoSair;
    }

    /**
     * @return the BotaoSalvarConsultorio
     */
    public javax.swing.JButton getBotaoSalvarConsultorio() {
        return BotaoSalvarConsultorio;
    }

    /**
     * @param BotaoSalvarConsultorio the BotaoSalvarConsultorio to set
     */
    public void setBotaoSalvarConsultorio(javax.swing.JButton BotaoSalvarConsultorio) {
        this.BotaoSalvarConsultorio = BotaoSalvarConsultorio;
    }

    /**
     * @return the BotaofluxodeCaixa
     */
    public javax.swing.JButton getBotaofluxodeCaixa() {
        return BotaofluxodeCaixa;
    }

    /**
     * @param BotaofluxodeCaixa the BotaofluxodeCaixa to set
     */
    public void setBotaofluxodeCaixa(javax.swing.JButton BotaofluxodeCaixa) {
        this.BotaofluxodeCaixa = BotaofluxodeCaixa;
    }

    /**
     * @return the Botaolist
     */
    public javax.swing.JButton getBotaolist() {
        return Botaolist;
    }

    /**
     * @param Botaolist the Botaolist to set
     */
    public void setBotaolist(javax.swing.JButton Botaolist) {
        this.Botaolist = Botaolist;
    }

    /**
     * @return the PanelConsultorio
     */
    public javax.swing.JPanel getPanelConsultorio() {
        return PanelConsultorio;
    }

    /**
     * @param PanelConsultorio the PanelConsultorio to set
     */
    public void setPanelConsultorio(javax.swing.JPanel PanelConsultorio) {
        this.PanelConsultorio = PanelConsultorio;
    }

    /**
     * @return the PanelDadosConsultorio
     */
    public javax.swing.JPanel getPanelDadosConsultorio() {
        return PanelDadosConsultorio;
    }

    /**
     * @param PanelDadosConsultorio the PanelDadosConsultorio to set
     */
    public void setPanelDadosConsultorio(javax.swing.JPanel PanelDadosConsultorio) {
        this.PanelDadosConsultorio = PanelDadosConsultorio;
    }

    /**
     * @return the PanelDadosEstoque
     */
    public javax.swing.JPanel getPanelDadosEstoque() {
        return PanelDadosEstoque;
    }

    /**
     * @param PanelDadosEstoque the PanelDadosEstoque to set
     */
    public void setPanelDadosEstoque(javax.swing.JPanel PanelDadosEstoque) {
        this.PanelDadosEstoque = PanelDadosEstoque;
    }

    /**
     * @return the PanelFinanceiro
     */
    public javax.swing.JPanel getPanelFinanceiro() {
        return PanelFinanceiro;
    }

    /**
     * @param PanelFinanceiro the PanelFinanceiro to set
     */
    public void setPanelFinanceiro(javax.swing.JPanel PanelFinanceiro) {
        this.PanelFinanceiro = PanelFinanceiro;
    }

    /**
     * @return the PanelPrincipal
     */
    public javax.swing.JPanel getPanelPrincipal() {
        return PanelPrincipal;
    }

    /**
     * @param PanelPrincipal the PanelPrincipal to set
     */
    public void setPanelPrincipal(javax.swing.JPanel PanelPrincipal) {
        this.PanelPrincipal = PanelPrincipal;
    }

    /**
     * @return the PanelRelatorio
     */
    public javax.swing.JPanel getPanelRelatorio() {
        return PanelRelatorio;
    }

    /**
     * @param PanelRelatorio the PanelRelatorio to set
     */
    public void setPanelRelatorio(javax.swing.JPanel PanelRelatorio) {
        this.PanelRelatorio = PanelRelatorio;
    }

    /**
     * @return the botaoSaidaEstoque
     */
    public javax.swing.JButton getBotaoSaidaEstoque() {
        return botaoSaidaEstoque;
    }

    /**
     * @param botaoSaidaEstoque the botaoSaidaEstoque to set
     */
    public void setBotaoSaidaEstoque(javax.swing.JButton botaoSaidaEstoque) {
        this.botaoSaidaEstoque = botaoSaidaEstoque;
    }

    /**
     * @return the botaocontapagar
     */
    public javax.swing.JButton getBotaocontapagar() {
        return botaocontapagar;
    }

    /**
     * @param botaocontapagar the botaocontapagar to set
     */
    public void setBotaocontapagar(javax.swing.JButton botaocontapagar) {
        this.botaocontapagar = botaocontapagar;
    }

    /**
     * @return the botaocontareceber
     */
    public javax.swing.JButton getBotaocontareceber() {
        return botaocontareceber;
    }

    /**
     * @param botaocontareceber the botaocontareceber to set
     */
    public void setBotaocontareceber(javax.swing.JButton botaocontareceber) {
        this.botaocontareceber = botaocontareceber;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @param jLabel2 the jLabel2 to set
     */
    public void setjLabel2(javax.swing.JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    /**
     * @return the jLabel3
     */
    public javax.swing.JLabel getjLabel3() {
        return jLabel3;
    }

    /**
     * @param jLabel3 the jLabel3 to set
     */
    public void setjLabel3(javax.swing.JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    /**
     * @return the jLabel4
     */
    public javax.swing.JLabel getjLabel4() {
        return jLabel4;
    }

    /**
     * @param jLabel4 the jLabel4 to set
     */
    public void setjLabel4(javax.swing.JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    /**
     * @return the jLabel5
     */
    public javax.swing.JLabel getjLabel5() {
        return jLabel5;
    }

    /**
     * @param jLabel5 the jLabel5 to set
     */
    public void setjLabel5(javax.swing.JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    /**
     * @return the jLabel6
     */
    public javax.swing.JLabel getjLabel6() {
        return jLabel6;
    }

    /**
     * @param jLabel6 the jLabel6 to set
     */
    public void setjLabel6(javax.swing.JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    /**
     * @return the jLabel7
     */
    public javax.swing.JLabel getjLabel7() {
        return jLabel7;
    }

    /**
     * @param jLabel7 the jLabel7 to set
     */
    public void setjLabel7(javax.swing.JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the jPanel10
     */
    public javax.swing.JPanel getjPanel10() {
        return jPanel10;
    }

    /**
     * @param jPanel10 the jPanel10 to set
     */
    public void setjPanel10(javax.swing.JPanel jPanel10) {
        this.jPanel10 = jPanel10;
    }

    /**
     * @return the jPanel2
     */
    public javax.swing.JPanel getjPanel2() {
        return jPanel2;
    }

    /**
     * @param jPanel2 the jPanel2 to set
     */
    public void setjPanel2(javax.swing.JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    /**
     * @return the jPanel4
     */
    public javax.swing.JPanel getjPanel4() {
        return jPanel4;
    }

    /**
     * @param jPanel4 the jPanel4 to set
     */
    public void setjPanel4(javax.swing.JPanel jPanel4) {
        this.jPanel4 = jPanel4;
    }

    /**
     * @return the jPanel5
     */
    public javax.swing.JPanel getjPanel5() {
        return jPanel5;
    }

    /**
     * @param jPanel5 the jPanel5 to set
     */
    public void setjPanel5(javax.swing.JPanel jPanel5) {
        this.jPanel5 = jPanel5;
    }

    /**
     * @return the jPanel6
     */
    public javax.swing.JPanel getjPanel6() {
        return jPanel6;
    }

    /**
     * @param jPanel6 the jPanel6 to set
     */
    public void setjPanel6(javax.swing.JPanel jPanel6) {
        this.jPanel6 = jPanel6;
    }

    /**
     * @return the jPanel7
     */
    public javax.swing.JPanel getjPanel7() {
        return jPanel7;
    }

    /**
     * @param jPanel7 the jPanel7 to set
     */
    public void setjPanel7(javax.swing.JPanel jPanel7) {
        this.jPanel7 = jPanel7;
    }

    /**
     * @return the jPanel8
     */
    public javax.swing.JPanel getjPanel8() {
        return jPanel8;
    }

    /**
     * @param jPanel8 the jPanel8 to set
     */
    public void setjPanel8(javax.swing.JPanel jPanel8) {
        this.jPanel8 = jPanel8;
    }

    /**
     * @return the jPanel9
     */
    public javax.swing.JPanel getjPanel9() {
        return jPanel9;
    }

    /**
     * @param jPanel9 the jPanel9 to set
     */
    public void setjPanel9(javax.swing.JPanel jPanel9) {
        this.jPanel9 = jPanel9;
    }

    /**
     * @return the labeltarefa
     */
    public javax.swing.JLabel getLabeltarefa() {
        return labeltarefa;
    }

    /**
     * @param labeltarefa the labeltarefa to set
     */
    public void setLabeltarefa(javax.swing.JLabel labeltarefa) {
        this.labeltarefa = labeltarefa;
    }

    /**
     * @return the lblcnpj
     */
    public javax.swing.JLabel getLblcnpj() {
        return lblcnpj;
    }

    /**
     * @param lblcnpj the lblcnpj to set
     */
    public void setLblcnpj(javax.swing.JLabel lblcnpj) {
        this.lblcnpj = lblcnpj;
    }

    /**
     * @return the lblemail
     */
    public javax.swing.JLabel getLblemail() {
        return lblemail;
    }

    /**
     * @param lblemail the lblemail to set
     */
    public void setLblemail(javax.swing.JLabel lblemail) {
        this.lblemail = lblemail;
    }

    /**
     * @return the lblendereco
     */
    public javax.swing.JLabel getLblendereco() {
        return lblendereco;
    }

    /**
     * @param lblendereco the lblendereco to set
     */
    public void setLblendereco(javax.swing.JLabel lblendereco) {
        this.lblendereco = lblendereco;
    }

    /**
     * @return the lblnome
     */
    public javax.swing.JLabel getLblnome() {
        return lblnome;
    }

    /**
     * @param lblnome the lblnome to set
     */
    public void setLblnome(javax.swing.JLabel lblnome) {
        this.lblnome = lblnome;
    }

    /**
     * @return the lbltelefone
     */
    public javax.swing.JLabel getLbltelefone() {
        return lbltelefone;
    }

    /**
     * @param lbltelefone the lbltelefone to set
     */
    public void setLbltelefone(javax.swing.JLabel lbltelefone) {
        this.lbltelefone = lbltelefone;
    }

    /**
     * @return the lbltelefone1
     */
    public javax.swing.JLabel getLbltelefone1() {
        return lbltelefone1;
    }

    /**
     * @param lbltelefone1 the lbltelefone1 to set
     */
    public void setLbltelefone1(javax.swing.JLabel lbltelefone1) {
        this.lbltelefone1 = lbltelefone1;
    }

    /**
     * @return the panelP
     */
    public javax.swing.JTabbedPane getPanelP() {
        return panelP;
    }

    /**
     * @param panelP the panelP to set
     */
    public void setPanelP(javax.swing.JTabbedPane panelP) {
        this.panelP = panelP;
    }

    /**
     * @return the txtUf
     */
    public javax.swing.JComboBox getTxtUf() {
        return txtUf;
    }

    /**
     * @param txtUf the txtUf to set
     */
    public void setTxtUf(javax.swing.JComboBox txtUf) {
        this.txtUf = txtUf;
    }

    /**
     * @return the txtbairro
     */
    public javax.swing.JTextField getTxtbairro() {
        return txtbairro;
    }

    /**
     * @param txtbairro the txtbairro to set
     */
    public void setTxtbairro(javax.swing.JTextField txtbairro) {
        this.txtbairro = txtbairro;
    }

    /**
     * @return the txtcelular
     */
    public javax.swing.JFormattedTextField getTxtcelular() {
        return txtcelular;
    }

    /**
     * @param txtcelular the txtcelular to set
     */
    public void setTxtcelular(javax.swing.JFormattedTextField txtcelular) {
        this.txtcelular = txtcelular;
    }

    /**
     * @return the txtcep
     */
    public javax.swing.JFormattedTextField getTxtcep() {
        return txtcep;
    }

    /**
     * @param txtcep the txtcep to set
     */
    public void setTxtcep(javax.swing.JFormattedTextField txtcep) {
        this.txtcep = txtcep;
    }

    /**
     * @return the txtcidade
     */
    public javax.swing.JTextField getTxtcidade() {
        return txtcidade;
    }

    /**
     * @param txtcidade the txtcidade to set
     */
    public void setTxtcidade(javax.swing.JTextField txtcidade) {
        this.txtcidade = txtcidade;
    }

    /**
     * @return the txtcnpj
     */
    public javax.swing.JFormattedTextField getTxtcnpj() {
        return txtcnpj;
    }

    /**
     * @param txtcnpj the txtcnpj to set
     */
    public void setTxtcnpj(javax.swing.JFormattedTextField txtcnpj) {
        this.txtcnpj = txtcnpj;
    }

    /**
     * @return the txtemail
     */
    public javax.swing.JTextField getTxtemail() {
        return txtemail;
    }

    /**
     * @param txtemail the txtemail to set
     */
    public void setTxtemail(javax.swing.JTextField txtemail) {
        this.txtemail = txtemail;
    }

    /**
     * @return the txtnomefantasia
     */
    public javax.swing.JTextField getTxtnomefantasia() {
        return txtnomefantasia;
    }

    /**
     * @param txtnomefantasia the txtnomefantasia to set
     */
    public void setTxtnomefantasia(javax.swing.JTextField txtnomefantasia) {
        this.txtnomefantasia = txtnomefantasia;
    }

    /**
     * @return the txtnumero
     */
    public javax.swing.JTextField getTxtnumero() {
        return txtnumero;
    }

    /**
     * @param txtnumero the txtnumero to set
     */
    public void setTxtnumero(javax.swing.JTextField txtnumero) {
        this.txtnumero = txtnumero;
    }

    /**
     * @return the txtrazao
     */
    public javax.swing.JTextField getTxtrazao() {
        return txtrazao;
    }

    /**
     * @param txtrazao the txtrazao to set
     */
    public void setTxtrazao(javax.swing.JTextField txtrazao) {
        this.txtrazao = txtrazao;
    }

    /**
     * @return the txtrua
     */
    public javax.swing.JTextField getTxtrua() {
        return txtrua;
    }

    /**
     * @param txtrua the txtrua to set
     */
    public void setTxtrua(javax.swing.JTextField txtrua) {
        this.txtrua = txtrua;
    }

    /**
     * @return the txttelefone
     */
    public javax.swing.JFormattedTextField getTxttelefone() {
        return txttelefone;
    }

    /**
     * @param txttelefone the txttelefone to set
     */
    public void setTxttelefone(javax.swing.JFormattedTextField txttelefone) {
        this.txttelefone = txttelefone;
    }


}
